local_backend: true

backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)

#folders
media_folder: "src/img/uploads"
public_folder: "/img/uploads"

#team member cms
collections:
- name: teamMembers  # Collection name
  label: Team Members # Collection label displayed in the CMS
  files:
    - label: "Team Members"
      name: "teamMembers"
      file: "src/_data/teamMembers.json"
      fields:
        - label: Team Members
          name: members
          widget: list
          collapsed: false
          fields:
            - {label: Name, name: name, widget: string}
            - {label: Position, name: position, widget: string}
            - {label: Bio, name: bio, widget: string, required: false }
            - {label: Photo, name: photo, widget: image, required: false }
- name: settings
  label: Settings
  files:
    - label: Site
      name: site
      file: src/_data/site.json
      fields:
        - { label: eMail, name: email, widget: string, required: false }
        - { label: Banner, name: banner, widget: string, required: false }