backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)

#folders
media_folder: "src/img/uploads"
public_folder: "/img"

#team member cms
collections:
- name: teamMembers  # Collection name
  label: Team Members # Collection label displayed in the CMS
  files:
    - label: "About Page"
      name: "about"
      file: "src/_data/teamMembers.json"
      fields:
        - {label: Title, name: title, widget: string}
        - {label: Intro, name: intro, widget: markdown}
        - label: Team
          name: team
          widget: list
          fields:
            - {label: Name, name: name, widget: string}
            - {label: Position, name: position, widget: string}
            - {label: Photo, name: photo, widget: image}

    #- { name: title, label: Title, widget: string } # Team member's job title
    #- { name: name, label: Name, widget: string } # Team member's full name
    #- { name: bio, label: Bio, widget: string } # Team member's biography
    #x`- { name: photo, label: Photo, widget: image, required: false } # Team member's photo (optional)

#     - { name: listOrder, label: "List Order", widget: string } # Team member's display order

